name: slovor

# Clean container naming: slovor-app, slovor-db

services:
  app:
    type: node:18
    scanner: false
    
    ports:
      - '3000:3000'
      - '54321:54321'
    
    build:
      - cd /app/slovor && npm install --silent --legacy-peer-deps || npm install --silent --force
    
    overrides:
      environment:
        NODE_ENV: development
        DATABASE_URL: postgres://postgres:postgres@database:5432/slovor
        NEXT_PUBLIC_SUPABASE_URL: https://rsywmmnxkvwvhgrgzlei.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeXdtbW54a3Z3dmhncmd6bGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMDA0MjAsImV4cCI6MjA4MDc3NjQyMH0.pNzBIic-uopmLaP8iU3VtQGasTmicyK-loUMbocYZq0
        WATCHPACK_POLLING: 'true'
        CHOKIDAR_USEPOLLING: 'true'
        CHOKIDAR_INTERVAL: 1000
        PORT: 3000
      
      # Resource limits for optimization
      deploy:
        resources:
          limits:
            cpus: '2'
            memory: 2G
          reservations:
            cpus: '0.5'
            memory: 512M
  
  database:
    type: postgres:15
    portforward: 5432
    
    creds:
      user: postgres
      password: postgres
      database: slovor
    
    config:
      database: slovor/supabase/migrations
    
    overrides:
      # Resource limits for database
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 1G
          reservations:
            cpus: '0.25'
            memory: 256M

tooling:
  npm:
    service: app
    description: Run npm commands inside container
    cmd: cd /app/slovor && npm
  
  node:
    service: app
    description: Run node commands
    cmd: cd /app/slovor && node
  
  npx:
    service: app
    description: Run npx commands (e.g., lando npx prisma)
    cmd: cd /app/slovor && npx
  
  dev:
    service: app
    description: Start Next.js dev server (localhost:3000)
    cmd: cd /app/slovor && npm run dev
  
  build:
    service: app
    description: Build production bundle
    cmd: cd /app/slovor && npm run build
  
  start:
    service: app
    description: Start production server
    cmd: cd /app/slovor && npm run start
  
  lint:
    service: app
    description: Run ESLint to check code
    cmd: cd /app/slovor && npm run lint
  
  lint:fix:
    service: app
    description: Auto-fix ESLint issues
    cmd: cd /app/slovor && npm run lint -- --fix
  
  format:
    service: app
    description: Format code with Prettier
    cmd: cd /app/slovor && npm run format
  
  test:
    service: app
    description: Run test suite
    cmd: cd /app/slovor && npm run test
  
  tsc:
    service: app
    description: TypeScript type checking (no emit)
    cmd: cd /app/slovor && npx tsc --noEmit
  
  health:
    service: app
    description: Quick lint + typecheck
    cmd: bash /app/scripts/health-check.sh
  
  doctor:
    service: app
    description: Full system diagnostics and troubleshooting
    cmd: bash /app/scripts/lando-doctor.sh
  
  setup-check:
    service: app
    description: Validate project structure
    cmd: bash /app/scripts/setup-check.sh
  
  setup-repair:
    service: app
    description: Auto-fix project structure issues
    cmd: bash /app/scripts/setup-repair.sh
  
  psql:
    service: database
    description: PostgreSQL interactive shell
    cmd: psql -U postgres slovor
  
  db-dump:
    service: database
    description: Export database to SQL
    cmd: pg_dump -U postgres slovor
  
  db-reset:
    service: database
    description: Drop and recreate database (WARNING: destroys data!)
    cmd: psql -U postgres -c 'DROP DATABASE IF EXISTS slovor; CREATE DATABASE slovor;'
  
  db-migrate:
    service: app
    description: Run Supabase migrations
    cmd: cd /app/slovor && supabase db push
  
  logs:
    service: app
    description: Show container logs (use Ctrl+C to exit)
    cmd: tail -f /var/log/* 2>/dev/null || echo "No logs available"
  
  urls:
    service: app
    description: Show all working URLs and connection info
    cmd: bash /app/scripts/show-urls.sh
  
  help:
    service: app
    description: Show detailed usage guide
    cmd: bash /app/scripts/post-start.sh
  
  cleanup:
    service: app
    description: Clean up unused Docker containers, images, volumes
    cmd: bash /app/scripts/docker-cleanup.sh
  
  cleanup:hard:
    service: app
    description: Nuclear cleanup - removes EVERYTHING (use with caution!)
    cmd: bash /app/scripts/docker-cleanup.sh --hard

events:
  post-start:
    - app: bash /app/scripts/post-start.sh
