name: slovor
recipe: nodejs

config:
  nodejs: '20'
  
services:
  # Node.js server for Next.js
  appserver:
    type: node:20
    port: 3000
    scanner:
      retry: 3
      timeout: 2000
    healthcheck:
      command: "node --version && npm --version"
      user: node
      retry: 3
      timeout: 5000
    overrides:
      environment:
        NODE_ENV: development
        NEXT_TELEMETRY_DISABLED: 1
  
  # PostgreSQL for local development
  database:
    type: postgres:15
    portforward: 5432
    creds:
      user: slovor
      password: slovor
      database: slovor_db
    healthcheck:
      command: "pg_isready -U slovor"
      user: postgres
      retry: 5
      timeout: 3000
  
  # Mailhog for email testing
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver

# Proxy configuration
proxy:
  appserver:
    - slovor.lndo.site:3000
  mailhog:
    - mail.slovor.lndo.site

# Automated health check events
events:
  # Pre-start - critical checks
  pre-start:
    - appserver: echo "🚀 Starting Slovor health checks..."
    - appserver: chmod +x /app/.lando/scripts/*.sh
    - appserver: /app/.lando/scripts/check-git.sh
    - appserver: /app/.lando/scripts/check-docker.sh
    - appserver: /app/.lando/scripts/validate-env.sh
  
  # Post-start - service checks
  post-start:
    - appserver: /app/.lando/scripts/check-nodejs.sh
    - database: /app/.lando/scripts/check-database.sh
    - appserver: /app/.lando/scripts/check-services.sh
    - appserver: echo "✅ Slovor environment ready!"
  
  # Pre-rebuild
  pre-rebuild:
    - appserver: echo "🔧 Validating configuration before rebuild..."
    - appserver: chmod +x /app/.lando/scripts/*.sh
    - appserver: /app/.lando/scripts/validate-env.sh
  
  # Post-rebuild
  post-rebuild:
    - appserver: npm install
    - appserver: echo "📦 Dependencies installed"
  
  # Pre-destroy
  pre-destroy:
    - appserver: echo "🗑️ Cleaning up Slovor environment..."

# Custom tooling commands
tooling:
  # Development commands
  npm:
    service: appserver
    cmd: npm
  
  node:
    service: appserver
    cmd: node
  
  next:
    service: appserver
    cmd: npm run
  
  # Health check commands
  check-all:
    service: appserver
    cmd:
      - /app/.lando/scripts/check-git.sh
      - /app/.lando/scripts/check-docker.sh
      - /app/.lando/scripts/check-wsl.sh
      - /app/.lando/scripts/check-nodejs.sh
      - /app/.lando/scripts/check-database.sh
      - /app/.lando/scripts/check-services.sh
      - /app/.lando/scripts/validate-env.sh
    description: "Run all health checks"
  
  check-env:
    service: appserver
    cmd: /app/.lando/scripts/validate-env.sh
    description: "Validate environment variables"
  
  check-deps:
    service: appserver
    cmd: npm outdated
    description: "Check for outdated dependencies"
  
  # Development server
  dev:
    service: appserver
    cmd: npm run dev
    description: "Start Next.js development server"
  
  build:
    service: appserver
    cmd: npm run build
    description: "Build production version"
  
  lint:
    service: appserver
    cmd: npm run lint
    description: "Run ESLint"
  
  test:
    service: appserver
    cmd: npm test
    description: "Run tests"
  
  # Database commands
  psql:
    service: database
    cmd: psql -U slovor slovor_db
    description: "Connect to PostgreSQL"
  
  db-import:
    service: database
    cmd: psql -U slovor slovor_db
    description: "Import database"
    options:
      file:
        description: SQL file to import
        alias:
          - f
  
  # Utility commands
  logs:
    service: appserver
    cmd: tail -f /tmp/*.log
    description: "View application logs"

# Environment files
env_file:
  - .env.local
  - .env
