name: slovor
recipe: node

config:
  node: '18'

services:
  appserver:
    type: node:18
    scanner: false
    
    ports:
      - '3000:3000'
      - '54321:54321'
    
    build:
      - cd slovor && npm install --silent --legacy-peer-deps || npm install --silent --force
    
    overrides:
      environment:
        NODE_ENV: development
        DATABASE_URL: postgres://postgres:postgres@database:5432/slovor
        NEXT_PUBLIC_SUPABASE_URL: https://rsywmmnxkvwvhgrgzlei.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeXdtbW54a3Z3dmhncmd6bGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMDA0MjAsImV4cCI6MjA4MDc3NjQyMH0.pNzBIic-uopmLaP8iU3VtQGasTmicyK-loUMbocYZq0
        WATCHPACK_POLLING: 'true'
        CHOKIDAR_USEPOLLING: 'true'
        CHOKIDAR_INTERVAL: 1000
  
  database:
    type: postgres:15
    portforward: 5432
    
    creds:
      user: postgres
      password: postgres
      database: slovor
    
    config:
      database: slovor/supabase/migrations

tooling:
  npm:
    service: appserver
    description: Run npm commands
    cmd: cd slovor && npm
  
  node:
    service: appserver
    description: Run node commands
    cmd: cd slovor && node
  
  npx:
    service: appserver
    description: Run npx commands
    cmd: cd slovor && npx
  
  dev:
    service: appserver
    description: Start Next.js development server
    cmd: cd slovor && npm run dev
  
  build:
    service: appserver
    description: Build Next.js for production
    cmd: cd slovor && npm run build
  
  start:
    service: appserver
    description: Start production server
    cmd: cd slovor && npm run start
  
  lint:
    service: appserver
    description: Run ESLint
    cmd: cd slovor && npm run lint
  
  lint:fix:
    service: appserver
    description: Auto-fix ESLint issues
    cmd: cd slovor && npm run lint -- --fix
  
  format:
    service: appserver
    description: Format code with Prettier
    cmd: cd slovor && npm run format
  
  test:
    service: appserver
    description: Run tests
    cmd: cd slovor && npm run test
  
  tsc:
    service: appserver
    description: TypeScript type checking
    cmd: cd slovor && npx tsc --noEmit
  
  health:
    service: appserver
    description: Quick health check (lint + typecheck)
    cmd: bash scripts/health-check.sh
  
  doctor:
    service: appserver
    description: Full system diagnostics
    cmd: bash scripts/lando-doctor.sh
  
  setup-check:
    service: appserver
    description: Validate project setup
    cmd: bash scripts/setup-check.sh
  
  setup-repair:
    service: appserver
    description: Auto-repair project setup
    cmd: bash scripts/setup-repair.sh
  
  psql:
    service: database
    description: Connect to PostgreSQL
    cmd: psql -U postgres slovor
  
  db-dump:
    service: database
    description: Dump database to stdout
    cmd: pg_dump -U postgres slovor
  
  db-reset:
    service: database
    description: Reset database
    cmd: psql -U postgres -c 'DROP DATABASE IF EXISTS slovor; CREATE DATABASE slovor;'
  
  db-migrate:
    service: appserver
    description: Run Supabase migrations
    cmd: cd slovor && supabase db push
  
  logs:
    service: appserver
    description: Show container logs
    cmd: tail -f /var/log/* 2>/dev/null || echo "No logs available"

events:
  pre-start:
    - appserver: bash scripts/pre-start-check.sh
  
  post-start:
    - appserver: bash scripts/post-start.sh
