import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeToggle } from "../components/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen bg-white text-gray-900 dark:bg-slate-950 dark:text-slate-50">
        <div className="flex min-h-screen flex-col bg-white/90 text-gray-900 dark:bg-slate-950 dark:text-slate-50">
          <header className="border-b border-slate-200 bg-white/80 px-4 py-4 shadow-sm backdrop-blur-sm dark:border-slate-800 dark:bg-slate-900/80">
            <div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4">
              <div className="text-2xl font-semibold text-brand">Slovor</div>
              <nav className="flex items-center gap-6 text-sm font-medium text-slate-600 dark:text-slate-300">
                <a href="#" className="transition hover:text-brand dark:hover:text-brand-light">
                  Browse
                </a>
                <a href="#" className="transition hover:text-brand dark:hover:text-brand-light">
                  Post ad
                </a>
                <a href="#" className="transition hover:text-brand dark:hover:text-brand-light">
                  Support
                </a>
                <ThemeToggle />
              </nav>
            </div>
          </header>
          <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
